apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      imagePullSecrets:
      - name: my-docker-secret
      containers:
      - name: frontend
        image: docker.io/himanshu7000/frontend:111
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://192.168.49.2:31603/api/tasks"
        ports:
        - containerPort: 3000
        
